
---

### Nagios Variables ###
nagios_username: nagiosadmin
nagios_password: changeme
nagios_http_port: 80
nagios_https_port: 443
admin_name_01: nagiosadmin
admin_email_01: nagios@localhost
### NRPE variables ###
nrpe_tcp_port: 5666
# threshold for # of processes
warning_proc: 900
critical_proc: 1000
