
---

### Nagios Variables ###
nagios_plugin_path: /usr/lib64/nagios/plugins
nagios_username: nagiosadmin
nagios_password: changeme
nagios_create_guest_user: true
nagios_ro_username: guest
nagios_ro_password: guest
nagios_http_port: 80
nagios_https_port: 443
admin_name_01: nagiosadmin
# change this to your email address if you want notifications
admin_email_01: nagios@localhost
### NRPE variables ###
nrpe_tcp_port: 5666
# threshold for # of processes
warning_proc: 900
critical_proc: 1000
# threshold for # of logged in users
warning_users: 15
critical_users: 30
### ELK options ###
# if you use my ELK playbook you'll need this for HTTP checks
# https://github.com/sadsfae/ansible-elk
kibana_user: admin
kibana_password: admin
### snmp options ###
# these are for dell idrac only
snmp_mib_path: /usr/share/snmp/mibs
snmp_opts: -v2c -c public
# these flag for strings to match failure, warn or ok
snmp_check_thresholds: --warn '$ALL$' --crit 'critical|nonRecoverable|fail' --ok 'ok|online|on|spunup|full|ready|enabled|unknown|presence'
# settings to check for idrac
# power supply
idrac_ps: true
# system fans and speed
idrac_fan: true
# CMOS battery
idrac_battery: true
# power redundancy
idrac_pu: true
# system memory
idrac_mem: true
# physical disk/RAID
idrac_disk: true
# RAID vdisk or JBOD
idrac_vdisk: true
# temperature
idrac_sensor: true
# system cpu
idrac_cpu: true
### SuperMicro IPMI Options ###
supermicro_ipmi_user: ADMIN
supermicro_ipmi_pass: ADMIN
supermicro_priv_level: user
supermicro_ipmicfg_path: /etc/supermicro-ipmi-config
# freeipmi settings
enable_legacy_output: on
enable_oem_data: on
disable_unrecognized_events: on
enable_workaround_flags: nochecksumcheck,noauthcodecheck
# supermicro individual checks
# you can make your own, I am only adding the
# bare basics and grouping by component
check_smc_cpu: true
check_smc_mem: true
check_smc_disk: true
check_smc_psu: true
check_smc_voltage: true
check_smc_temp: true
# please see full mapping of sensor id below, you will
# specify the sensors you want to monitor in a csv format:
# https://github.com/thomas-krenn/check_ipmi_sensor_v3
supermicro_check_cpu: 4,71,339,406
supermicro_check_mem: 2617,2684,2751,2818
supermicro_check_disk: 3957,4024
supermicro_check_psu: 3756,3823
supermicro_check_voltage: 2416,3086,3019,3153,2483,2550
supermicro_check_temp: 205,272
#### sensor ID    |  Component | Measurement ####
#4 | CPU1 Temp |
#71 | CPU2 Temp |
#138 | PCH Temp |
#205 | System Temp |
#272 | Peripheral Temp |
#339 | Vcpu1VRM Temp |
#406 | Vcpu2VRM Temp |
#473 | VmemABVRM Temp |
#540 | VmemCDVRM Temp |
#607 | VmemEFVRM Temp |
#674 | VmemGHVRM Temp |
#741 | P1-DIMMA1 Temp |
#875 | P1-DIMMB1 Temp |
#1277 | P2-DIMME1 Temp |
#1411 | P2-DIMMF1 Temp |
#1813 | FAN1 | Fan |
#1880 | FAN2 | Fan |
#1947 | FAN3 | Fan |
#2014 | FAN4 | Fan |
#2081 | FANA | Fan |
#2215 | 12V | Voltage |
#2282 | 5VCC | Voltage |
#2349 | 3.3VCC | Voltage |
#2416 | VBAT | Voltage |
#2483 | Vcpu1 | Voltage |
#2550 | Vcpu2 | Voltage |
#2617 | VDIMMAB | Voltage |
#2684 | VDIMMCD | Voltage |
#2751 | VDIMMEF | Voltage |
#2818 | VDIMMGH | Voltage |
#2885 | 5VSB | Voltage |
#2952 | 3.3VSB | Voltage |
#3019 | 1.5V PCH | Voltage |
#3086 | 1.2V BMC | Voltage |
#3153 | 1.05V PCH | Voltage |
#3220 | Chassis Intru | Physical Security |
#3756 | PS1 Status | Power Supply |
#3823 | PS2 Status | Power Supply |
#3890 | MB/AOM_SAS Temp | Temperature |
#3957 | HDD Temp        | Temperature |
#4024 | HDD Status      | Drive Slot |
